"""initial control plane schema

Revision ID: 656bd67b04a6
Revises:
Create Date: 2026-09-10 19:57:08.238422
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '656bd67b04a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('clinic_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_clinic_id'), 'audit_events', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_audit_events_org_id'), 'audit_events', ['org_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('artifact_url', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('signing_public_key', sa.Text(), nullable=False),
    sa.Column('min_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('clinics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_clinic_org_code')
    )
    op.create_index(op.f('ix_clinics_org_id'), 'clinics', ['org_id'], unique=False)
    op.create_table('edge_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'device_fingerprint', name='uq_edge_clinic_device'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_edge_nodes_clinic_id'), 'edge_nodes', ['clinic_id'], unique=False)
    op.create_table('lookup_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_org_id', sa.String(length=36), nullable=False),
    sa.Column('requester_user_id', sa.String(length=36), nullable=True),
    sa.Column('source_clinic_id', sa.String(length=36), nullable=False),
    sa.Column('match_token', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=80), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requester_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_lookup_requests_match_token'), 'lookup_requests', ['match_token'], unique=False)
    op.create_index(op.f('ix_lookup_requests_requester_org_id'), 'lookup_requests', ['requester_org_id'], unique=False)
    op.create_index(op.f('ix_lookup_requests_source_clinic_id'), 'lookup_requests', ['source_clinic_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'username', name='uq_user_org_username')
    )
    op.create_index(op.f('ix_users_clinic_id'), 'users', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('aggregate_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_aggregate_snapshots_clinic_id'), 'aggregate_snapshots', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_aggregate_snapshots_edge_id'), 'aggregate_snapshots', ['edge_id'], unique=False)
    op.create_table('update_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'edge_id', name='uq_update_idem_edge')
    )
    op.create_index(op.f('ix_update_jobs_edge_id'), 'update_jobs', ['edge_id'], unique=False)
    op.create_index(op.f('ix_update_jobs_release_id'), 'update_jobs', ['release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_jobs_release_id'), table_name='update_jobs')
    op.drop_index(op.f('ix_update_jobs_edge_id'), table_name='update_jobs')
    op.drop_table('update_jobs')
    op.drop_index(op.f('ix_aggregate_snapshots_edge_id'), table_name='aggregate_snapshots')
    op.drop_index(op.f('ix_aggregate_snapshots_clinic_id'), table_name='aggregate_snapshots')
    op.drop_table('aggregate_snapshots')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lookup_requests_source_clinic_id'), table_name='lookup_requests')
    op.drop_index(op.f('ix_lookup_requests_requester_org_id'), table_name='lookup_requests')
    op.drop_index(op.f('ix_lookup_requests_match_token'), table_name='lookup_requests')
    op.drop_table('lookup_requests')
    op.drop_index(op.f('ix_edge_nodes_clinic_id'), table_name='edge_nodes')
    op.drop_table('edge_nodes')
    op.drop_index(op.f('ix_clinics_org_id'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_table('releases')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_events_org_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_clinic_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
