const state={key:sessionStorage.getItem('yk_platform_key')||'',view:'dashboard',data:{}};
const $=s=>document.querySelector(s);
const nav=[['dashboard','概览','⌂'],['organizations','组织门店','▦'],['edges','终端设备','◫'],['releases','版本升级','⇧'],['aggregates','经营汇总','▥'],['lookups','授权查询','⌕'],['users','成员角色','♙'],['audit','审计日志','≡']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—';
const badge=v=>`<span class="status ${String(v||'pending').toLowerCase()}">${esc(v)}</span>`;
const empty=(t,c)=>`<div class="empty-state"><strong>${esc(t)}</strong><span>${esc(c)}</span></div>`;
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Platform-Key':state.key,...(options.headers||{})}});let b=null;try{b=await r.json()}catch(_){}if(!r.ok)throw new Error(b?.detail||b?.error||`HTTP ${r.status}`);return b;}
function toast(m,e=false){const t=$('#toast');t.textContent=m;t.style.background=e?'#8f2727':'#102b25';t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2500);}
function showLogin(m=''){$('#loginView').hidden=false;$('#appView').hidden=true;$('#loginError').textContent=m;}
function showApp(){$('#loginView').hidden=true;$('#appView').hidden=false;renderNav();loadAll();}
function header(t,s){$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s;}
function renderNav(){$('#nav').innerHTML=nav.map(([id,l,i])=>`<button data-view="${id}" class="${state.view===id?'active':''}"><span class="nav-icon">${i}</span><span>${l}</span></button>`).join('');document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{state.view=x.dataset.view;renderNav();render();});}
async function loadAll(){try{const [summary,organizations,clinics,edges,releases,updates,lookups,users,audit]=await Promise.all([api('/api/v1/dashboard/summary'),api('/api/v1/orgs'),api('/api/v1/clinics'),api('/api/v1/edge/nodes'),api('/api/v1/releases'),api('/api/v1/updates'),api('/api/v1/lookup-requests'),api('/api/v1/users'),api('/api/v1/audit?limit=200')]);state.data={summary,organizations,clinics,edges,releases,updates,lookups,users,audit};$('#connectionLabel').textContent='控制面在线';render();}catch(e){$('#connectionLabel').textContent='连接异常';toast(e.message,true);}}
const table=(h,r)=>r.length?`<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.join('')}</tbody></table></div>`:'';
function render(){({dashboard,organizations,edges,releases,aggregates,lookups,users,audit}[state.view]||dashboard)();bind();}
function dashboard(){header('运营总览','连锁门店、设备、版本和待处理事项');const s=state.data.summary||{};const cards=[['组织',s.organizations||0],['门店',s.clinics||0],['终端在线',`${s.online_edges||0}/${s.active_edges||0}`],['待处理',(s.pending_updates||0)+(s.pending_lookups||0)]];$('#content').innerHTML=`<div class="metric-grid">${cards.map(([l,v])=>`<article class="metric-card"><div class="metric-label">${l}</div><div class="metric-value">${v}</div><div class="metric-note">控制面实时数据</div></article>`).join('')}</div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>门店运行状态</h2><p>设备最后在线时间和版本</p></div><button class="secondary-button" data-action="refresh">刷新</button></div>${edgeTable(true)}</section><section class="panel"><div class="panel-head"><div><h2>近期授权查询</h2><p>不包含患者明细</p></div></div><div class="panel-body">${(state.data.lookups||[]).slice(-5).reverse().map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><strong>${esc(x.reason)}</strong><div style="margin-top:5px">${badge(x.status)} <span style="color:var(--muted);font-size:12px">${fmt(x.created_at)}</span></div></div>`).join('')||empty('暂无授权查询','跨店查询会显示在这里。')}</div></section></div>`;}
function edgeTable(compact=false){const rows=(state.data.edges||[]).map(x=>`<tr><td>${esc(x.clinic_name)}</td><td>${esc(x.hostname||'—')}</td>${compact?'':`<td>${esc(x.org_id)}</td>`}<td>${esc(x.version||'—')}</td><td>${badge(x.status)}</td><td>${fmt(x.last_seen_at)}</td></tr>`);return rows.length?table(['门店','主机',...compact?[]:['组织'],'版本','状态','最后在线'],rows):empty('暂无终端设备','注册边缘设备后显示。');}
function organizations(){header('组织与门店','管理租户、门店和数据归属');const o=state.data.organizations||[],c=state.data.clinics||[];$('#content').innerHTML=`<div class="toolbar"><div><h2>组织与门店</h2><p>组织代表连锁品牌，门店代表数据节点。</p></div><div class="toolbar-actions"><button class="secondary-button" data-action="new-org">新建组织</button><button class="primary-button" data-action="new-clinic">新建门店</button></div></div><section class="panel">${table(['组织','编码','状态','门店数','创建时间'],o.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.code)}</td><td>${badge(x.status)}</td><td>${c.filter(y=>y.org_id===x.id).length}</td><td>${fmt(x.created_at)}</td></tr>`))||empty('还没有组织','先创建组织。')}</section><section class="panel" style="margin-top:16px"><div class="panel-head"><div><h2>门店列表</h2><p>每门店对应一个本地节点</p></div></div>${table(['门店','编码','组织','状态','创建时间'],c.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.code)}</td><td>${esc(o.find(y=>y.id===x.org_id)?.name||x.org_id)}</td><td>${badge(x.status)}</td><td>${fmt(x.created_at)}</td></tr>`))||empty('还没有门店','创建门店后注册设备。')}</section>`;}
function edges(){header('终端设备','查看门店节点、在线状态和版本');$('#content').innerHTML=`<section class="panel">${edgeTable()}</section>`;}
function releases(){header('版本升级','签名版本和灰度更新任务');const r=state.data.releases||[],u=state.data.updates||[];$('#content').innerHTML=`<div class="toolbar"><div><h2>版本发布</h2><p>Ed25519 签名 + SHA-256 校验</p></div><button class="primary-button" data-action="new-release">发布版本</button></div><section class="panel">${table(['版本','最低版本','状态','SHA-256','发布时间'],r.map(x=>`<tr><td><strong>${esc(x.version)}</strong></td><td>${esc(x.min_version)}</td><td>${badge(x.status)}</td><td>${esc(x.sha256.slice(0,16))}…</td><td>${fmt(x.created_at)}</td></tr>`))||empty('暂无版本','发布版本后创建更新任务。')}</section><section class="panel" style="margin-top:16px"><div class="panel-head"><div><h2>更新任务</h2><p>下发、验证和回滚状态</p></div></div>${table(['设备','版本','状态','尝试','更新时间'],u.map(x=>`<tr><td>${esc(x.edge_id)}</td><td>${esc(x.release?.version||'—')}</td><td>${badge(x.status)}</td><td>${x.attempts}</td><td>${fmt(x.updated_at)}</td></tr>`))||empty('暂无更新任务','任务创建后显示。')}</section>`;}
function aggregates(){header('经营汇总','只看数字，不拉取患者明细');const o=state.data.organizations||[];$('#content').innerHTML=`<div class="toolbar"><div><h2>经营汇总</h2><p>接诊量、营收、患者数和库存预警。</p></div><div class="toolbar-actions"><select id="aggregateOrg" class="filter-select"><option value="">选择组织</option>${o.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><button class="primary-button" data-action="aggregate">加载</button></div></div><section class="panel"><div id="aggregateResult" class="panel-body">${empty('等待加载','请选择组织。')}</div></section>`;}
function lookups(){header('授权查询','跨店访问必须经源门店确认');const x=state.data.lookups||[];$('#content').innerHTML=`<section class="panel">${table(['原因','源门店','状态','申请时间','操作'],x.map(i=>`<tr><td>${esc(i.reason)}</td><td>${esc(i.source_clinic_id)}</td><td>${badge(i.status)}</td><td>${fmt(i.created_at)}</td><td>${i.status==='pending'?`<button class="secondary-button" data-action="approve" data-id="${i.id}">批准</button> <button class="ghost-button" data-action="deny" data-id="${i.id}">拒绝</button>`:'—'}</td></tr>`))||empty('暂无授权查询','跨店查询申请会显示。')}</section>`;}
function users(){header('成员角色','管理控制面账号与角色');const x=state.data.users||[];$('#content').innerHTML=`<div class="toolbar"><div><h2>成员角色</h2><p>机构负责人、店长、医生、药师、财务、审计员。</p></div><button class="primary-button" data-action="new-user">新增成员</button></div><section class="panel">${table(['用户名','显示名称','角色','状态','创建时间'],x.map(i=>`<tr><td><strong>${esc(i.username)}</strong></td><td>${esc(i.display_name||'—')}</td><td>${esc(i.role)}</td><td>${badge(i.status)}</td><td>${fmt(i.created_at)}</td></tr>`))||empty('暂无成员','新增成员后分配角色。')}</section>`;}
function audit(){header('审计日志','管理元数据留痕，不含患者文本');const x=state.data.audit||[];$('#content').innerHTML=`<section class="panel">${table(['动作','操作者','资源','组织 / 门店','时间'],x.map(i=>`<tr><td><strong>${esc(i.action)}</strong></td><td>${esc(i.actor_id)}</td><td>${esc(i.resource_type)}</td><td>${esc(i.org_id||'—')} / ${esc(i.clinic_id||'—')}</td><td>${fmt(i.created_at)}</td></tr>`))||empty('暂无审计记录','管理操作发生后显示。')}</section>`;}
const field=(l,id,type='text',p='')=>`<div class="field"><label>${l}</label><input id="${id}" type="${type}" placeholder="${p}"></div>`;
function modal(title,body,handler){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalError').textContent='';$('#modal')._submit=handler;$('#modal').showModal();}
function bind(){document.querySelectorAll('[data-action]').forEach(x=>x.onclick=()=>action(x.dataset.action,x));}
async function action(name,el){const o=state.data.organizations||[];if(name==='refresh')return loadAll();if(name==='new-org')return modal('新建组织',field('组织名称','orgName')+field('组织编码','orgCode','text','chain-demo'),async()=>{await api('/api/v1/orgs',{method:'POST',body:JSON.stringify({name:$('#orgName').value,code:$('#orgCode').value})});toast('组织已创建')});if(name==='new-clinic')return modal('新建门店',`<div class="field"><label>组织</label><select id="clinicOrg">${o.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div>`+field('门店名称','clinicName')+field('门店编码','clinicCode'),async()=>{await api('/api/v1/clinics',{method:'POST',body:JSON.stringify({org_id:$('#clinicOrg').value,name:$('#clinicName').value,code:$('#clinicCode').value,address:''})});toast('门店已创建')});if(name==='new-user')return modal('新增成员',`<div class="field"><label>组织</label><select id="userOrg">${o.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div>`+field('用户名','userName')+field('显示名称','displayName')+`<div class="field"><label>角色</label><select id="role"><option value="org_owner">机构负责人</option><option value="store_manager">店长</option><option value="doctor">医生</option><option value="pharmacist">药师</option><option value="finance">财务</option><option value="auditor">审计员</option></select></div>`,async()=>{await api('/api/v1/users',{method:'POST',body:JSON.stringify({org_id:$('#userOrg').value,username:$('#userName').value,display_name:$('#displayName').value,role:$('#role').value})});toast('成员已创建')});if(name==='new-release')return modal('发布版本',field('版本号','version')+field('发布包 URL','artifactUrl')+field('SHA-256','sha256')+field('最低版本','minVersion','text','4.0.0'),async()=>{await api('/api/v1/releases',{method:'POST',body:JSON.stringify({version:$('#version').value,artifact_url:$('#artifactUrl').value,sha256:$('#sha256').value,min_version:$('#minVersion').value})});toast('版本已发布')});if(name==='aggregate'){const org=$('#aggregateOrg').value;if(!org)return toast('请选择组织',true);const r=await api(`/api/v1/aggregates/summary?org_id=${encodeURIComponent(org)}`);const e=Object.entries(r.totals||{});$('#aggregateResult').innerHTML=e.length?`<div class="metric-grid">${e.map(([k,v])=>`<article class="metric-card"><div class="metric-label">${esc(k)}</div><div class="metric-value">${v}</div></article>`).join('')}</div>`:empty('暂无聚合数据','门店上报后显示。');return;}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();state.key=$('#platformKey').value.trim();try{await api('/api/v1/dashboard/summary');sessionStorage.setItem('yk_platform_key',state.key);showApp();}catch(x){$('#loginError').textContent=x.message;}};
$('#refreshButton').onclick=loadAll;$('#logoutButton').onclick=()=>{sessionStorage.clear();state.key='';showLogin();};$('#settingsButton').onclick=()=>modal('连接设置',field('平台管理密钥','settingKey','password'),async()=>{state.key=$('#settingKey').value.trim()||state.key;sessionStorage.setItem('yk_platform_key',state.key);toast('密钥已更新')});$('#modalClose').onclick=$('#modalCancel').onclick=()=>$('#modal').close();$('#modalForm').onsubmit=async e=>{e.preventDefault();try{await $('#modal')._submit();$('#modal').close();await loadAll();}catch(x){$('#modalError').textContent=x.message;}};if(state.key)showApp();else showLogin();
